
import React from 'react';
import { Observation, TaxonomicGroup, Status, Protocol } from './types';


export const TAXON_LOGOS: Record<TaxonomicGroup, string> = {
    [TaxonomicGroup.BIRD]: '/Logo/Oiseaux.png',
    [TaxonomicGroup.MAMMAL]: '/Logo/Mammifères.png',
    [TaxonomicGroup.MARINE_MAMMAL]: '/Logo/Mammifères marin.png',
    [TaxonomicGroup.REPTILE]: '/Logo/reptiles.png',
    [TaxonomicGroup.AMPHIBIAN]: '/Logo/Amphibiens.png',
    [TaxonomicGroup.ODONATE]: '/Logo/Odonates.png',
    [TaxonomicGroup.BUTTERFLY]: '/Logo/Papillons de jour.png',
    [TaxonomicGroup.MOTH]: '/Logo/Papillons de nuit.png',
    [TaxonomicGroup.ORTHOPTERA]: '/Logo/Orthoptères.png',
    [TaxonomicGroup.HYMENOPTERA]: '/Logo/Hyménoptères.png',
    [TaxonomicGroup.MANTIS]: '/Logo/Mantes.png',
    [TaxonomicGroup.CICADA]: '/Logo/Cigales.png',
    [TaxonomicGroup.HETEROPTERA]: '/Logo/Punaises.png',
    [TaxonomicGroup.COLEOPTERA]: '/Logo/Coléoptères.png',
    [TaxonomicGroup.NEUROPTERA]: '/Logo/Nevroptères.png',
    [TaxonomicGroup.DIPTERA]: '/Logo/Diptères.png',
    [TaxonomicGroup.PHASMID]: '/Logo/Phasmes.png',
    [TaxonomicGroup.ARACHNID]: '/Logo/Araignées.png',
    [TaxonomicGroup.FISH]: '/Logo/Poissons.png',
    [TaxonomicGroup.CRUSTACEAN]: '/Logo/Crustacés.png',
    [TaxonomicGroup.CHIROPTERA]: '/Logo/Chiroptères.png',
    [TaxonomicGroup.ORCHID]: '/Logo/Orchidées.png',
    [TaxonomicGroup.BOTANY]: '/Logo/Botanique générale.png',
    [TaxonomicGroup.OTHER]: '', // No logo for "Autre"
};


export const INITIAL_OBSERVATIONS: Observation[] = [
    {
        id: '1672531200000',
        speciesName: 'Mésange charbonnière',
        latinName: 'Parus major',
        taxonomicGroup: TaxonomicGroup.BIRD,
        date: '2023-01-01',
        time: '10:00',
        count: 2,
        location: 'Jardin familial',
        gps: { lat: 48.8566, lon: 2.3522 },
        municipality: 'Paris',
        department: '75',
        country: 'France',
        altitude: 35,
        comment: 'Couple sur la mangeoire.',
        status: Status.LC,
        atlasCode: '',
        protocol: Protocol.OPPORTUNIST,
    },
    {
        id: '1675209600000',
        speciesName: 'Pinson des arbres',
        latinName: 'Fringilla coelebs',
        taxonomicGroup: TaxonomicGroup.BIRD,
        date: '2023-02-01',
        time: '12:30',
        count: 5,
        location: 'Forêt de Fontainebleau',
        gps: { lat: 48.404, lon: 2.697 },
        municipality: 'Fontainebleau',
        department: '77',
        country: 'France',
        altitude: 80,
        comment: 'Groupe chantant.',
        status: Status.LC,
        atlasCode: 'C',
        protocol: Protocol.OPPORTUNIST,
    },
    {
        id: '1677628800000',
        speciesName: 'Écureuil roux',
        latinName: 'Sciurus vulgaris',
        taxonomicGroup: TaxonomicGroup.MAMMAL,
        date: '2023-03-01',
        time: '15:45',
        count: 1,
        location: 'Parc de Sceaux',
        gps: { lat: 48.775, lon: 2.29 },
        municipality: 'Sceaux',
        department: '92',
        country: 'France',
        altitude: 60,
        comment: 'Grimpe à un chêne.',
        status: Status.LC,
        atlasCode: '',
        protocol: Protocol.OPPORTUNIST,
    }
];
